apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstack
  namespace: demo-system
  labels:
    app: "logstack"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "logstack"
  template:
    metadata:
      labels:
        app: "logstack"
    spec:
      serviceAccountName: logstack
      volumes:
        - emptyDir: {}
          name: tmp-dir
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.6.1
        command: ["etcd"]
        args:
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://localhost:2379
        - --listen-metrics-urls=http://0.0.0.0:2381
        - --data-dir=/tmp
        - --name=frostbeat-etcd
        ports:
        - containerPort: 2379
          hostPort: 2379
          protocol: TCP
      - name: frostbeat
        image: kind.local/frostbeat:latest
        imagePullPolicy: Never
        args:
        - --etcd-servers=http://localhost:2379
        - --debug=true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
      - name: auger
        image: kind.local/auger:latest
        imagePullPolicy: Never
        args:
        - --etcd-servers=http://localhost:2379
        - --debug=true
        - --port=8082
        ports:
        - name: http
          containerPort: 8082
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000

