kind: ServiceAccount
apiVersion: v1
metadata:
  name: logstack
  namespace: demo-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logstack-role
  namespace: demo-system
rules:
  - apiGroups: [""]
    resources: 
      - "pods"
      - "pods/log"
    verbs: ["get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logstack-rolebinding
  namespace: demo-system
subjects:
  - kind: ServiceAccount
    name: logstack
    namespace: demo-system
roleRef:
  kind: Role
  name: logstack-role
  apiGroup: rbac.authorization.k8s.io  